### ISSUE TITLE
Stephanie Consuegra 2020 Spring

### ISSUE THREAD

**Issue by sconsueg** [Klepac-Ceraj-Lab/lab_docs#11]
SERP Student 2019-2020

**Comment by kescobo** [comment]
Hi Steph, can you fill out the template? When you hit "New Issue" you should have the option of selecting "Lab Policies Agreement"

**Comment by sconsueg** [comment]
Hi Kevin, 

For some reason that wasn’t showing up :( What should I do? 

Sincerely,

Stephanie Consuegra
Wellesley College 2022
